SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
# Radius of the player's ship
PLAYER_RADIUS = 20
# width of the lines that draw the player's ship
LINE_WIDTH = 2
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200

# Asteroid info
ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE_SECONDS = 0.8
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS